### ISSUE TITLE
Min height inherit on inner blocks causing issue with some other blocks

### ISSUE THREAD

**Issue by shramee** [pootlepress/caxton#196]
These style,

```CSS
.block-editor-inner-blocks,
.block-editor-block-list__layout {
	min-height: inherit;
}
```

could go inside the blocks that need it (like layout/cover block).

❗ Need to test all blocks after updating.
